# Análise e Visualização de Dados

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import glob
import os

In [5]:
df_pl = pd.read_csv("../dados/processado/apartments_pl_processed.csv")
df_rent = pd.read_csv("../dados/processado/apartments_rent_processed.csv")

In [6]:
df_pl.head(5)

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,collegeDistance,pharmacyDistance,ownership,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,mes
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,1.097,0.413,condominium,yes,yes,yes,no,yes,415000,8
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,2011.0,53.442692,14.559690,...,1.404,0.205,cooperative,no,yes,yes,no,yes,395995,8
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,1974.0,53.452222,14.553333,...,1.857,0.280,condominium,no,no,no,no,no,565000,8
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,2020.0,53.435100,14.532900,...,0.310,0.087,condominium,yes,yes,no,no,yes,640000,8
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,1980.0,53.410278,14.503611,...,2.138,0.514,condominium,no,no,no,no,no,759000,8

In [7]:
df_rent.head(5)

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,collegeDistance,pharmacyDistance,ownership,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,mes
0,2a1a6db97ff122d6bc148abb6f0e498a,szczecin,blockOfFlats,52.0,2.0,3.0,3.0,2008.0,53.460535,14.545416,...,2.200,0.307,condominium,yes,yes,no,no,no,3500,11
1,996722490efcb4b34d48bb84a9a72838,szczecin,Desconecido,43.4,2.0,3.0,4.0,2011.0,53.435746,14.560764,...,0.714,0.211,condominium,no,yes,no,no,no,1900,11
2,50d75c688530b9a61ba505301e0b94a9,szczecin,apartmentBuilding,32.6,2.0,5.0,6.0,2021.0,53.421582,14.541572,...,0.689,0.192,condominium,no,yes,yes,no,no,2500,11
3,9b187f4203adabf466fd08610d8f4e5e,szczecin,apartmentBuilding,72.0,3.0,6.0,6.0,2014.0,53.450010,14.547230,...,1.387,0.315,condominium,no,yes,yes,no,yes,2999,11
4,ba4d70d65d1024ee13929ca82bfc92f6,szczecin,blockOfFlats,52.0,2.0,1.0,3.0,2006.0,53.427400,14.488100,...,3.003,0.458,condominium,yes,no,no,no,no,2300,11

## apartments_pl_processed